site_name: Webots Simulink Bridge
site_url: https://harunkurtdev.github.io/webots-simulink
site_description: Documentation for bridging Webots and Simulink for robotics simulation.
site_author: Harun KURT
site_keywords: Webots, Simulink, Robotics, Simulation, Bridge

nav:
  - Home: index.md
  - Installation:
      - Requirements: installation/requirements.md
      - Setup: installation/setup.md
  - Usage:
      - Connecting Webots and Simulink: usage/connecting.md
      - Running Simulations: usage/running.md
      - Data Exchange: usage/data_exchange.md
  - Advanced:
      - Customizing the Bridge: advanced/customization.md
      - Debugging: advanced/debugging.md
  - Examples:
      - Inverted Pendulum Example: examples/inverted-pendulum.md
      - Wheel Chair Example: examples/wheel-chair.md
      - Crazy Drone Example: examples/crazyflie-drone.md
      - BlueBoat USV Example: examples/blueboat-usv.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - References: references.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@harunkurtdev
    # - icon: simple/linkedin
      # link: https://linkedin.com/in/

copyright: Copyright &copy; 2025 harunkurtdev